version: "3.3"

services:
  backend:
    build: services/backend
    container_name: dr_backend
    ports:
      - 5000:5000

  frontend:
    build: services/frontend
    container_name: dr_frontend
    ports:
      - 8080:5173
    depends_on:
      - backend
